# Comment Toxicity Severity Rater
- group by the same comment and find out if that comment is more often rated as more/ less toxic 
- transform the input data to be more / less toxic 0 and 1 // train on these


In [2]:
#!pip install alt-profanity-check
!pip install joblib
!pip install scikit-learn
#install tweet-preprocessor to clean tweets
!pip install tweet-preprocessor


zsh:1: command not found: pip
zsh:1: command not found: pip
zsh:1: command not found: pip


In [2]:
import sklearn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# remove special characters using the regular expression library
# updated with . and = 
import re

#set up punctuations we want to be replaced
REPLACE_NO_SPACE = re.compile("(\*)|(\=\=)|(\~) | (\=) | (\.\.\.) |(\;)|(\:)|(\!)|(\')|(\?)|(\,)|(\")|(\|)|(\()|(\))|(\[)|(\])|(\%)|(\$)|(\>)|(\<)|(\{)|(\})")
REPLACE_WITH_SPACE = re.compile(" (<br\s/><br\s/?)| (\n\n) | (\n) |(\.) |(-)|(/)|(:). ")

#re.escape (* )

# re.sub() // natalie uses this more often

# regex has a method to escape the char properly 
re.escape


# gridsearchcv() // can be slow 
if have a few val, can use 

# use randomsearch() // possible range // faster 

In [4]:
import preprocessor as p

# custum function to clean the dataset (combining tweet_preprocessor and reguar expression)
def clean_tweets(df):
  tempArr = []
  for line in df:
    # send to tweet_processor
    tmpL = p.clean(line)
    # remove puctuation
    tmpL = REPLACE_NO_SPACE.sub("", tmpL.lower()) # convert all tweets to lower cases
    tmpL = REPLACE_WITH_SPACE.sub(" ", tmpL)
    tempArr.append(tmpL)
  return tempArr

In [5]:
original_data = pd.read_csv("./data/validation_data.csv")

data_to_test = pd.read_csv('./data/comments_to_score.csv')

In [6]:
pd.set_option('display.max_columns', None)

original_data.head()



worker                                         less_toxic  \
0     313            This article sucks \n\nwoo woo wooooooo   
1     188  "And yes, people should recognize that but the...   
2      82   Western Media?\n\nYup, because every crime in...   
3     347  And you removed it! You numbskull! I don't car...   
4     539   smelly vagina \n\nBluerasberry why don't you ...   

                                          more_toxic  
0  WHAT!!!!!!!!?!?!!?!?!!?!?!?!?!!!!!!!!!!!!!!!!!...  
1   Daphne Guinness \n\nTop of the mornin' my fav...  
2  "Atom you don't believe actual photos of mastu...  
3  You seem to have sand in your vagina.\n\nMight...  
4           hey \n\nway to support nazis, you racist

In [7]:
#original_data.iloc[0]
original_data['more_toxic'][0]

'WHAT!!!!!!!!?!?!!?!?!!?!?!?!?!!!!!!!!!!!!!!!!!!!!!!!!??????????????????????????????????????????????????????!!!!!!=\nWHER IS YOUR SEXY PIC GONE FROM YOUR MAIN PAGE???????? put it back'

In [8]:
cleaned_data = original_data
cleaned_data

worker                                         less_toxic  \
0         313            This article sucks \n\nwoo woo wooooooo   
1         188  "And yes, people should recognize that but the...   
2          82   Western Media?\n\nYup, because every crime in...   
3         347  And you removed it! You numbskull! I don't car...   
4         539   smelly vagina \n\nBluerasberry why don't you ...   
...       ...                                                ...   
30103     461  I'm sorry. I'm not an admin. I will give you t...   
30104     527  I'm sorry. I'm not an admin. I will give you t...   
30105     352  wow...\nare you out of your mind, how was my e...   
30106     311  wow...\nare you out of your mind, how was my e...   
30107      54  wow...\nare you out of your mind, how was my e...   

                                              more_toxic  
0      WHAT!!!!!!!!?!?!!?!?!!?!?!?!?!!!!!!!!!!!!!!!!!...  
1       Daphne Guinness \n\nTop of the mornin' my fav...  
2      "Atom you don't believe actual photos of mastu...  
3      You seem to have sand in your vagina.\n\nMight...  
4               hey \n\nway to support nazis, you racist  
...                                                  ...  
30103                             get out my large penis  
30104                             get out my large penis  
30105                       Piss off you slant eyed-gook  
30106                       Piss off you slant eyed-gook  
30107                       Piss off you slant eyed-gook  

[30108 rows x 3 columns]

In [9]:
clean_less_toxic = clean_tweets(original_data["less_toxic"])
cleaned_data['less_toxic'] = pd.DataFrame(clean_less_toxic)
#cleaned_data

In [10]:
clean_more_toxic = clean_tweets(original_data["more_toxic"])
cleaned_data['more_toxic'] = pd.DataFrame(clean_more_toxic)
cleaned_data

worker                                         less_toxic  \
0         313                this article sucks woo woo wooooooo   
1         188  and yes people should recognize that but they ...   
2          82  western mediayup because every crime in the en...   
3         347  and you removed it you numbskull i dont care w...   
4         539  smelly vagina bluerasberry why dont you be a m...   
...       ...                                                ...   
30103     461  im sorry im not an admin i will give you three...   
30104     527  im sorry im not an admin i will give you three...   
30105     352  wow...are you out of your mind how was my edit...   
30106     311  wow...are you out of your mind how was my edit...   
30107      54  wow...are you out of your mind how was my edit...   

                                              more_toxic  
0      what=wher is your sexy pic gone from your main...  
1      daphne guinness top of the mornin my favourite...  
2      atom you dont believe actual photos of masturb...  
3      you seem to have sand in your vagina.might wan...  
4                    hey way to support nazis you racist  
...                                                  ...  
30103                             get out my large penis  
30104                             get out my large penis  
30105                       piss off you slant eyed gook  
30106                       piss off you slant eyed gook  
30107                       piss off you slant eyed gook  

[30108 rows x 3 columns]

In [11]:
grouped_df_less = original_data.groupby(['less_toxic']).size()

print(grouped_df_less.index[0])
#grouped_df_less.values[0]

grouped_df_more = original_data.groupby(['more_toxic']).size()
#grouped_df_more.index[0]

print(len(grouped_df_less.values))
print(len(grouped_df_more.values))




   cody porter dies while foolishly copying kimimaro kaguya    okay we need to add this seriously i mean we added the crap about a freakin death note so i believe we definitely should add this especially since a little ten year old baka died     news report t  c     this has already been discussed before here check that discussion for the news reports and why we decided not to include it also he was imitating gaara not kimmimaro warranting the nickname of s& sand hero from  b  got a present for ya  mission log   heres where it went wrong  no he was copying kimimaro dont believe every little detail from a reporter who calls it nerutu sand ninjas.. gaara was using armor he wasnt actually buried sorry if i sound aggressive but i know my naruto   i seriosly dont want to be rude but these parents and a whole ton of other people are clueless they all think that naruto is some weird kids show like doraemon or pokmon no it was made for teenagers well in the of age or older and was serialized i

# Transform the original data to be grouped by the comment and rate as more toxic or less toxic based on the more often rated comment

# todo: implement jason's sort indices method


In [12]:
n_less = len(grouped_df_less.index)
n_more = len(grouped_df_more.index)

comment = []
score = []
#jason jan 29: sort the indices (think of the comments as numbers, == and > and <, if a < b, then up the a), if the indices are the same - do logic,when more index is less than the less index // inc whatever is lesser than the other index. Once the threshold to the "more valued" index, then append the rest into the new transformed 
for i in range(n_more):
    if grouped_df_more.index[i] not in grouped_df_less.index:
            comment.append(grouped_df_more.index[i])
            score.append(1)
            continue
    for j in range(n_less): 
        
        if grouped_df_less.index[j] == grouped_df_more.index[i]:
            comment.append(grouped_df_less.index[j])
            if grouped_df_more.values[i] >= grouped_df_less.values[j]:
                score.append(1)
            else:
                score.append(0)


In [13]:
print(len(comment))
print(len(score))

11644
11644


In [14]:
trans = pd.DataFrame(comment, columns = ['comment'])
trans['score'] = pd.DataFrame(score, columns = ['score'])
trans

comment  score
0                  =            =                    ...      1
1         cody porter dies while foolishly copying ki...      0
2         i get it the page is about all the doomsday...      0
3         invention   what on earth are you talking a...      0
4         is she black   why dose it matter what race...      1
...                                                  ...    ...
11639  zora you seem to assume that i have not done m...      1
11640  zulfiqar ali bhutto stop vandalizing zulfiqar ...      1
11641  zzzzzzz.. youre a real bore now go bore someon...      0
11642  ~whats with you that youre so annoying and pro...      1
11643  ~~its okay of course for them to have their ow...      1

[11644 rows x 2 columns]

In [15]:
# these comments are all categorized as less toxic 
for j in range(n_less): 
        if grouped_df_less.index[j] not in grouped_df_more.index:
            comment.append(grouped_df_less.index[j])
            score.append(0)

In [16]:
print(len(comment))
print(len(score))

14208
14208


In [17]:
trans = pd.DataFrame(comment, columns = ['comment'])
trans['score'] = pd.DataFrame(score, columns = ['score'])


In [18]:
#testing to see if the transformation data only appears once now (expected). Want every comment
# to be either more or less toxic
pd.DataFrame(trans.groupby(['comment']).size().values).describe() 



0
count  14208.0
mean       1.0
std        0.0
min        1.0
25%        1.0
50%        1.0
75%        1.0
max        1.0

In [19]:
trans.groupby(['score']).size()

score
0    6765
1    7443
dtype: int64

In [20]:
trans

comment  score
0                  =            =                    ...      1
1         cody porter dies while foolishly copying ki...      0
2         i get it the page is about all the doomsday...      0
3         invention   what on earth are you talking a...      0
4         is she black   why dose it matter what race...      1
...                                                  ...    ...
14203  yuber youre the pov pusher and stalking my con...      0
14204  yuberplease do something about yubers constant...      0
14205  ywhy arnt i allowed to contribute when i just ...      0
14206  zionist jewplease stop spreadin your lies bias...      0
14207  ~i heard that dick gephardt was actually presi...      0

[14208 rows x 2 columns]

In [21]:

from sklearn.model_selection import train_test_split

# extract the labels from the train data
y = trans.score.values
X = trans.comment.values

# use 60% for the training, 20% validation, and 20% for the test
x_train_all, x_test, y_train_all, y_test = train_test_split(X, y, 
                                                    stratify=y, 
                                                    random_state=1, 
                                                    test_size=0.2, shuffle=True)
# train
x_train = x_train_all[int(x_train_all.shape[0]/4):]
y_train = y_train_all[int(y_train_all.shape[0]/4):]

#valid
x_val = x_train_all[:int(x_train_all.shape[0]/4)]
y_val = y_train_all[:int(y_train_all.shape[0]/4)]



In [22]:
y_train

array([0, 1, 1, ..., 0, 0, 0])

In [23]:
#clean the input for predition data
cleaned_text = clean_tweets(data_to_test['text'])

data_to_test['text'] = pd.DataFrame(cleaned_text)
data_to_test

comment_id                                               text
0         114890   gjalexei you asked about whether there is an ...
1         732895  looks like be have an abuser  can you please l...
2        1139051  i confess to having complete and apparently bl...
3        1434512  freuds ideas are certainly much discussed toda...
4        2084821  it is not just you this is a laundry list of s...
...          ...                                                ...
7532   504235362                       go away you annoying vandal.
7533   504235566                             this user is a vandal.
7534   504308177   sorry to sound like a pain but one by followi...
7535   504570375  well its pretty fucking irrelevant now im unbl...
7536   504598250  the team name is great britain and northern ir...

[7537 rows x 2 columns]

In [24]:
# extract the labels from the train data
#y = trans.score.values
#X = trans.comment.values

from sklearn.feature_extraction.text import CountVectorizer

# initalize vectorizer: vectorize tweets for model building
vectorizer = CountVectorizer(binary=True, stop_words='english') #stop_words removed: a, the

# learn a vocabulary dictionary of all tokens in the raw documents
vectorizer.fit(list(x_train_all) + list(x_test) + list(data_to_test["text"].values))
    

# transform documents to document-term matrix
x_train_vec = vectorizer.transform(x_train)
x_train_val_vec = vectorizer.transform(x_train_all)
x_val_vec = vectorizer.transform(x_val)


x_test_vec = vectorizer.transform(x_test)




In [25]:
x_train_val_vec.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [26]:
(x_train_val_vec.toarray().shape) 

(11366, 46974)

In [27]:
(x_train_val_vec.toarray()[0].size) #number of unique words

46974

In [28]:

from sklearn.feature_extraction.text import CountVectorizer

# initalize vectorizer: vectorize tweets for model building
vectorizer = CountVectorizer(binary=True, stop_words='english') #stop_words removed: a, the

# learn a vocabulary dictionary of all tokens in the raw documents
vectorizer.fit(list(cleaned_data['less_toxic'].values) + list(cleaned_data['more_toxic'].values))
    

# transform documents to document-term matrix
less_tox_vec = vectorizer.transform(cleaned_data['less_toxic'])
more_tox_vec = vectorizer.transform(cleaned_data['more_toxic'])


#concatenate on the last dim
# same rows, vec from first one on the sec vec

# zip and train  on the dataframe -- 1 column for more toxic, 1 for less toxic


# concatenate on the last dim
# same rows, vec from first one on the sec vec

# TODO: LOOK AT SLACK WITH NATALIE FOR NORMAL MODEL TRAIN 2) LISTEN TO THE PHONE RECORDING FOR LSTM AND LOGISTIC REGRESSION TRAIN 

In [29]:
less_tox_vec

<30108x46974 sparse matrix of type '<class 'numpy.int64'>'
	with 800699 stored elements in Compressed Sparse Row format>

# 2 features ? 

for part 1 and part 2? 

## concatenate the whole vector count

# but how to tell the model that feature 1 of column 1 is for lesser -- how to put a label on that ? when the same row has another column for more toxic

# comparing the classification accuracy of basic models // should place after the cross-validated

In [102]:
from scipy.stats import rankdata
# make a function to score the prediction and compare if the "lesser" toxic rated is lower prob of rated toxicity
def comp_toxicity (model, less_tox_val_vec, more_tox_val_vec):
  '''
   model is the trained model to be evaluated against the less and more toxic comments
    objective is to see if more toxic comments have a higher score
  
  less_tox_val_vec and more_tox_val_vec are the respective column in dataframe that contains the comments vectorized
  '''
  result = res = np.zeros((1,2))
  for i in range(cleaned_data.shape[0]):
    result = rankdata([model.predict_proba(less_tox_val_vec[i]).tolist()[0][1], 
             model.predict_proba(more_tox_val_vec[i]).tolist()[0][1]], method = 'ordinal' )
    result -= 1
    #print(result)
    res += result
    #print(res[0])
    
    
  print ('final result: ',res[0])
  return res[0]



In [69]:
clf = RandomForestClassifier(n_estimators=10, random_state=1)
clf.fit(x_train_vec,y_train )


RandomForestClassifier(n_estimators=10, random_state=1)

In [103]:
comp_toxicity(clf, less_tox_vec, more_tox_vec)

final result:  [ 7179. 22929.]


array([ 7179., 22929.])

In [106]:
from sklearn import neighbors

clf = neighbors.KNeighborsClassifier(n_neighbors=3)
clf.fit(x_train_vec,y_train )
comp_toxicity(clf, less_tox_vec, more_tox_vec)

final result:  [ 5961. 24147.]


array([ 5961., 24147.])

In [107]:
#Logistic Regression

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(x_train_vec,y_train )
comp_toxicity(clf, less_tox_vec, more_tox_vec)

final result:  [ 8404. 21704.]


array([ 8404., 21704.])

In [108]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(x_train_vec,y_train )
comp_toxicity(clf, less_tox_vec, more_tox_vec)

final result:  [ 8448. 21660.]


array([ 8448., 21660.])

In [109]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(x_train_vec,y_train )
comp_toxicity(clf, less_tox_vec, more_tox_vec)

final result:  [ 9085. 21023.]


array([ 9085., 21023.])

In [115]:
C = 1.0
clf = svm.SVC(kernel='linear', C=C, probability = True)
clf.fit(x_train_vec,y_train )
comp_toxicity(clf, less_tox_vec, more_tox_vec)

clf = svm.SVC(kernel='rbf', C=C, probability = True)
clf.fit(x_train_vec,y_train )
comp_toxicity(clf, less_tox_vec, more_tox_vec)

clf = svm.SVC(kernel='sigmoid', C=C, probability = True)
clf.fit(x_train_vec,y_train )
comp_toxicity(clf, less_tox_vec, more_tox_vec)

clf = svm.SVC(kernel='poly', C=C, probability = True)
clf.fit(x_train_vec,y_train )
comp_toxicity(clf, less_tox_vec, more_tox_vec)




final result:  [ 8481. 21627.]
final result:  [ 8003. 22105.]
final result:  [10310. 19798.]
final result:  [ 8481. 21627.]


array([ 8481., 21627.])

# cross validation on different models

In [35]:
#Random Forest

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score


clf = RandomForestClassifier(n_estimators=10, random_state=1)
cv_scores = cross_val_score(clf, x_train_val_vec, y_train_all, cv=10)

print ('random forest: ',cv_scores.mean())

random forest:  0.609096631238619


In [ ]:
#KNN choosing best neighbour number 

from sklearn import neighbors


for n in range(1, 15):
    clf = neighbors.KNeighborsClassifier(n_neighbors=n)
    cv_scores = cross_val_score(clf, x_train_val_vec, y_train_all, cv=10)
    print (n, cv_scores.mean())
    
#k = 8 , 3 are first and sec place for best predictor respectively

1 0.5512023548502979
2 0.5609703073321194
3 0.5720559725990065
4 0.5686223320574281
5 0.5624646958266751
6 0.571175613487433
7 0.5613207167366556
8 0.5728458260557187
9 0.5587683643638435
10 0.5665985358058643
11 0.5599116466609685
12 0.5651014375611629
13 0.5590337650352423
14 0.5629917809407013


In [ ]:
#KNN 

from sklearn import neighbors

clf = neighbors.KNeighborsClassifier(n_neighbors=8)
cv_scores = cross_val_score(clf, x_train_val_vec, y_train_all, cv=10)

cv_scores.mean()

0.5728458260557187

In [ ]:
#Logistic Regression

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
cv_scores = cross_val_score(clf, x_train_val_vec, y_train_all, cv=10)
cv_scores.mean()

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


0.6199204572200131

In [ ]:
#Naive Bayes
#usually not the best performance, but fast to train
from sklearn import preprocessing

from sklearn.naive_bayes import MultinomialNB

#scaler = preprocessing.MinMaxScaler()
scaler = preprocessing.MaxAbsScaler() #don't really need scaling since the input is already binary 
training_inputs_minmax = scaler.fit_transform(x_train_val_vec)

clf = MultinomialNB()
cv_scores = cross_val_score(clf, training_inputs_minmax, y_train_all, cv=10)

print ('minmax scaled Baye\'s: ',cv_scores.mean())

minmax scaled Baye's:  0.6206232889863367


In [110]:
#SVM with kernel tuning

from sklearn import svm

C = 1.0
svc = svm.SVC(kernel='linear', C=C)
cv_scores = cross_val_score(svc, x_train_val_vec, y_train_all, cv=10)
print ('linear kernel', cv_scores.mean())


svc = svm.SVC(kernel='rbf', C=C)
cv_scores = cross_val_score(svc, x_train_val_vec, y_train_all, cv=10)
cv_scores.mean()
print ('rbf kernel', cv_scores.mean())


svc = svm.SVC(kernel='sigmoid', C=C)
cv_scores = cross_val_score(svc, x_train_val_vec, y_train_all, cv=10)
cv_scores.mean()
print ('sigmoid kernel', cv_scores.mean())

svc = svm.SVC(kernel='poly', C=C)
cv_scores = cross_val_score(svc, x_train_val_vec, y_train_all, cv=10)
cv_scores.mean()
print ('poly kernel', cv_scores.mean())

linear kernel 0.6077753570676478
rbf kernel 0.6370746466485809
sigmoid kernel 0.6134956396249086
poly kernel 0.5293857693212928


# try on colab: keras lstm, xgb 

In [ ]:
!pip install xgboost

In [ ]:
import xgboost as xgb

clf = xgb.XGBClassifier( eta = 0.6 ,objective = 'multi:softmax', num_class = 2) #eta higher starts losing acc -- lower is slower
cv_scores = cross_val_score(clf, x_train_val_vec, y_train_all, cv=10)
print (cv_scores.mean())

0.6200051562674198


In [ ]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, GlobalAveragePooling1D
from tensorflow.keras.layers import LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(x_train)
vocab_size = len(tokenizer.word_index) + 1

sequences_train = tokenizer.texts_to_sequences(x_train)
padded_train = sequence.pad_sequences(sequences_train, padding='post', maxlen = 50) 

sequences_val = tokenizer.texts_to_sequences(x_val)
padded_val = sequence.pad_sequences(sequences_val, padding='post', maxlen = 50) 

In [ ]:
#y_train
#y_val
print(padded_val.shape)
print(padded_train.shape)
padded_val[0]

(2841, 50)
(8525, 50)


array([   36,     8,    39,   324,   115,   217,  5268,    47,   484,
         184,     1,   210,    36,    25,    15,    39,  6877,   115,
         146,    36,     8,    39,   206, 11772,   178,    33,    30,
         115,    38,   255,    24,   118,   307,    39,    64, 11111,
           5,   574,    66, 10237,    57,   162,  2130,     0,     0,
           0,     0,     0,     0,     0], dtype=int32)

In [ ]:
model = Sequential()
model.add(Embedding(vocab_size, 128)) 
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2)) #128 intermediate recurrent neurons in the lstm layer // maybe need more or less
#single layer 25 does better
#model.add(Dense(64, activation='relu'))
#model.add(Dense(32, activation='relu'))
#model.add(Dense(16, activation='relu'))
model.add(Dense(16, activation='relu'))

model.add(Dense(1, activation='sigmoid')) #sigmoid becuz binary classification

In [ ]:
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy']) #optimization

In [ ]:
my_callbacks = [
                EarlyStopping(patience = 3, monitor = 'val_loss'),
                ModelCheckpoint(filepath='model.{epoch:02d}-{val_loss:.2f}.h5') #edit name: as diff parameter changed
]

# further optimization: https://keras.io/api/callbacks/, https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/EarlyStopping#args


In [ ]:
model.fit(padded_train, y_train,
          batch_size=32, #num of data to use per step size
          epochs=15,
          verbose=2,
          validation_data=(padded_val, y_val), callbacks = my_callbacks)

Epoch 1/15
267/267 - 58s - loss: 0.6894 - accuracy: 0.5390 - val_loss: 0.6675 - val_accuracy: 0.5790 - 58s/epoch - 216ms/step
Epoch 2/15
267/267 - 55s - loss: 0.6357 - accuracy: 0.6425 - val_loss: 0.6712 - val_accuracy: 0.6054 - 55s/epoch - 205ms/step
Epoch 3/15
267/267 - 55s - loss: 0.4658 - accuracy: 0.7974 - val_loss: 0.7750 - val_accuracy: 0.6107 - 55s/epoch - 204ms/step
Epoch 4/15
267/267 - 53s - loss: 0.2933 - accuracy: 0.8887 - val_loss: 0.9297 - val_accuracy: 0.6149 - 53s/epoch - 200ms/step


In [ ]:
#best model from callback 
from tensorflow import keras
model = keras.models.load_model('model.02-0.62.h5')

In [ ]:
#pad the test set prediction: 7:35 from https://www.youtube.com/watch?v=Y_hzMnRXjhI


#model prediction on the padded test set 

# accuracy still very bad: consider grabbing other dataset to train OR adding more dense layers with the bigger dataset

## trying with different maxlen in lstm 
was using padding maxlen = 20, 59.87%
maxlen = 80, got about 55%
maxlen = 50, got 55.79%

## adding dense intermediate layers with maxlen = 50 
model.add(Dense(25, activation='relu')) // 61%

//not as good: 60.47%
model.add(Dense(90, activation='relu'))
model.add(Dense(60, activation='relu'))
model.add(Dense(24, activation='relu'))

//60.15%
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))

//61.46%, 60.08
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))

//60.65%
model.add(Dense(16, activation='relu'))

//60.26%
model.add(Dense(25, activation='relu'))
model.add(Dense(8, activation='relu'))

//59%
model.add(Dense(8, activation='relu'))

In [ ]:
score, acc = model.evaluate(x_test, y_test,
                            batch_size=32,
                            verbose=2)
print('Test score:', score)
print('Test accuracy:', acc)