# Comment Toxicity Severity Rater
- group by the same comment and find out if that comment is more often rated as more/ less toxic 
- transform the input data to be more / less toxic 0 and 1 // train on these


In [1]:
#!pip install alt-profanity-check
!pip install joblib
!pip install scikit-learn
#install tweet-preprocessor to clean tweets
!pip install tweet-preprocessor


In [2]:
import sklearn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random


In [3]:
# remove special characters using the regular expression library
# updated with . and = 
import re

#set up punctuations we want to be replaced
REPLACE_NO_SPACE = re.compile("(\*)|(\=\=)|(\~) | (\=) | (\.\.\.) |(\;)|(\:)|(\!)|(\')|(\?)|(\,)|(\")|(\|)|(\()|(\))|(\[)|(\])|(\%)|(\$)|(\>)|(\<)|(\{)|(\})")
REPLACE_WITH_SPACE = re.compile(" (<br\s/><br\s/?)| (\n\n) | (\n) |(\.) |(-)|(/)|(:). ")

#re.escape (* )

# Regex improvement / suggestions from Natalie:
re.sub() // natalie uses this more often

re.escape //regex has a method to escape the char properly 

gridsearchcv() // can be slow, if have a few val, can use 

randomsearch() // possible range to test // faster 

In [4]:
import preprocessor as p

# custum function to clean the dataset (combining tweet_preprocessor and reguar expression)
def clean_tweets(df):
  tempArr = []
  for line in df:
    # send to tweet_processor
    tmpL = p.clean(line)
    # remove puctuation
    tmpL = REPLACE_NO_SPACE.sub("", tmpL.lower()) # convert all tweets to lower cases
    tmpL = REPLACE_WITH_SPACE.sub(" ", tmpL)
    tempArr.append(tmpL)
  return tempArr

In [5]:
original_data = pd.read_csv("./data/validation_data.csv")

data_to_test = pd.read_csv('./data/comments_to_score.csv')

In [6]:
pd.set_option('display.max_columns', None)

original_data.head()



worker                                         less_toxic  \
0     313            This article sucks \n\nwoo woo wooooooo   
1     188  "And yes, people should recognize that but the...   
2      82   Western Media?\n\nYup, because every crime in...   
3     347  And you removed it! You numbskull! I don't car...   
4     539   smelly vagina \n\nBluerasberry why don't you ...   

                                          more_toxic  
0  WHAT!!!!!!!!?!?!!?!?!!?!?!?!?!!!!!!!!!!!!!!!!!...  
1   Daphne Guinness \n\nTop of the mornin' my fav...  
2  "Atom you don't believe actual photos of mastu...  
3  You seem to have sand in your vagina.\n\nMight...  
4           hey \n\nway to support nazis, you racist

In [7]:
#original_data.iloc[0]
#original_data['more_toxic'][0]

In [8]:
cleaned_data = original_data
cleaned_data

worker                                         less_toxic  \
0         313            This article sucks \n\nwoo woo wooooooo   
1         188  "And yes, people should recognize that but the...   
2          82   Western Media?\n\nYup, because every crime in...   
3         347  And you removed it! You numbskull! I don't car...   
4         539   smelly vagina \n\nBluerasberry why don't you ...   
...       ...                                                ...   
30103     461  I'm sorry. I'm not an admin. I will give you t...   
30104     527  I'm sorry. I'm not an admin. I will give you t...   
30105     352  wow...\nare you out of your mind, how was my e...   
30106     311  wow...\nare you out of your mind, how was my e...   
30107      54  wow...\nare you out of your mind, how was my e...   

                                              more_toxic  
0      WHAT!!!!!!!!?!?!!?!?!!?!?!?!?!!!!!!!!!!!!!!!!!...  
1       Daphne Guinness \n\nTop of the mornin' my fav...  
2      "Atom you don't believe actual photos of mastu...  
3      You seem to have sand in your vagina.\n\nMight...  
4               hey \n\nway to support nazis, you racist  
...                                                  ...  
30103                             get out my large penis  
30104                             get out my large penis  
30105                       Piss off you slant eyed-gook  
30106                       Piss off you slant eyed-gook  
30107                       Piss off you slant eyed-gook  

[30108 rows x 3 columns]

In [9]:
clean_less_toxic = clean_tweets(original_data["less_toxic"])
cleaned_data['less_toxic'] = pd.DataFrame(clean_less_toxic)
#cleaned_data

In [10]:
clean_more_toxic = clean_tweets(original_data["more_toxic"])
cleaned_data['more_toxic'] = pd.DataFrame(clean_more_toxic)
cleaned_data

worker                                         less_toxic  \
0         313                this article sucks woo woo wooooooo   
1         188  and yes people should recognize that but they ...   
2          82  western mediayup because every crime in the en...   
3         347  and you removed it you numbskull i dont care w...   
4         539  smelly vagina bluerasberry why dont you be a m...   
...       ...                                                ...   
30103     461  im sorry im not an admin i will give you three...   
30104     527  im sorry im not an admin i will give you three...   
30105     352  wow...are you out of your mind how was my edit...   
30106     311  wow...are you out of your mind how was my edit...   
30107      54  wow...are you out of your mind how was my edit...   

                                              more_toxic  
0      what=wher is your sexy pic gone from your main...  
1      daphne guinness top of the mornin my favourite...  
2      atom you dont believe actual photos of masturb...  
3      you seem to have sand in your vagina.might wan...  
4                    hey way to support nazis you racist  
...                                                  ...  
30103                             get out my large penis  
30104                             get out my large penis  
30105                       piss off you slant eyed gook  
30106                       piss off you slant eyed gook  
30107                       piss off you slant eyed gook  

[30108 rows x 3 columns]

In [11]:
np.random.seed(0)
    
cleaned_data_shuffle_row = cleaned_data.sample(frac = 1, random_state = 0)


cleaned_data_shuffle_row

worker                                         less_toxic  \
14331       9  its not so much about the english language its...   
17914     431  just read what mr george mcfly said here that ...   
14390     338   a barnstar for you the original barnstar your...   
24121     386  i am one who thinks that zappas dad was of ara...   
22424     397     a cup of coffee for you get fuckd with coffee    
...       ...                                                ...   
13123     422   please stop your disruptive editing if you co...   
19648     293  dude you both are dumb in the heavier than hea...   
9845      347                            then i guess i eat poop   
10799     728  i thought you were the administrator can you f...   
2732      132  not set in new york  why when i deleted the ca...   

                                              more_toxic  
14331                       i hate drmies he is an idiot  
17914  i fuckingg love tacosthere the fuckingg best b...  
14390    fuck you fuck you motherfucker go die in a hole  
24121                 jimbo wales is a gay little fucker  
22424  dude im not angry at you i just think youre a ...  
...                                                  ...  
13123               youre a mathsci sockpuppet arent you  
19648  mahmoud ahmadinejadi added the categoryanti se...  
9845   racisttrying to whitewash the terrorists fine ...  
10799  just because she has light skin doesnt mean an...  
2732   what the hell is that thing on the electoral m...  

[30108 rows x 3 columns]

In [12]:
total_row = cleaned_data_shuffle_row.shape[0]
total_row

30108

In [13]:
train_data = cleaned_data_shuffle_row[:int(total_row*0.6)]
train_data = train_data.reset_index(drop = True)
train_data

worker                                         less_toxic  \
0           9  its not so much about the english language its...   
1         431  just read what mr george mcfly said here that ...   
2         338   a barnstar for you the original barnstar your...   
3         386  i am one who thinks that zappas dad was of ara...   
4         397     a cup of coffee for you get fuckd with coffee    
...       ...                                                ...   
18059      30  i cant imagine anything more depressing than d...   
18060     141   give a reason when you accuse someone of vand...   
18061     118  additional evidence to above one of the collec...   
18062     526  omg i am obssessed with twilight and it is my ...   
18063     338  jack and jill come on delanoy wheres your sens...   

                                              more_toxic  
0                           i hate drmies he is an idiot  
1      i fuckingg love tacosthere the fuckingg best b...  
2        fuck you fuck you motherfucker go die in a hole  
3                     jimbo wales is a gay little fucker  
4      dude im not angry at you i just think youre a ...  
...                                                  ...  
18059  i dont give a fuck.. it will get reposted so y...  
18060  bullshit=there was no violation you removed fa...  
18061  because you are a fggt do i know you because y...  
18062  hey gwernol yeah youre a schmuck face thats wh...  
18063  so you assholes are high on power like george ...  

[18064 rows x 3 columns]

In [14]:
val_data = cleaned_data_shuffle_row[int(total_row*0.6): int(total_row * 0.8)]
val_data = val_data.reset_index(drop = True)
val_data

worker                                         less_toxic  \
0        283   an important message block me i can live with...   
1        652  gibnews the truth it is a lie which has been f...   
2        504  the germaine greer quote is highly appropriate...   
3        567  if this is the sort of community that wants to...   
4        261  this is bull this is y2k all over again this i...   
...      ...                                                ...   
6017     655  racisma word describing characteristics of a p...   
6018     472  you are not sorry one damned bit you have yet ...   
6019     131   its all about termination not branches branch...   
6020     530                  thats really shameless weaseling.   
6021     465  ok im stopping now tide roll wouldnt want to m...   

                                             more_toxic  
0     blockedyour recent behaviour has been utterly ...  
1     fuck you fred fuck you you bitch ass punk u ca...  
2                                i hate you i hate you.  
3     please keep your two cents to yourselfi wasnt ...  
4     the cherokee comment was a concern because jvm...  
...                                                 ...  
6017  just for the record castro apologised for his ...  
6018   so called fan sites on wikipedia include info...  
6019   mgnbar what is a stupid act hi consensus mean...  
6020   moot is a faggot he claims you are a sock pup...  
6021  deaf culture is full of a bunch of jerks who w...  

[6022 rows x 3 columns]

In [15]:
test_data = cleaned_data_shuffle_row[int(total_row*0.8):]
test_data = test_data.reset_index(drop = True)
test_data

worker                                         less_toxic  \
0        126   palestinian christians hi   you have made doz...   
1        130                        stop vandalizing wikipedia.   
2        728  age you might want to reconsider advertising y...   
3        398    the good thing is that you didnt call me mf lol   
4          2  the bottom line is that you are a biased contr...   
...      ...                                                ...   
6017     422   please stop your disruptive editing if you co...   
6018     293  dude you both are dumb in the heavier than hea...   
6019     347                            then i guess i eat poop   
6020     728  i thought you were the administrator can you f...   
6021     132  not set in new york  why when i deleted the ca...   

                                             more_toxic  
0      re reply at jimbo youre right here about cond...  
1     you have been blocked for vandalism to userpag...  
2     no not really i picked the name to wind up the...  
3     shitush shitush who are youyou are blatantly a...  
4     was jesus gayif you say no how do you know wer...  
...                                                 ...  
6017               youre a mathsci sockpuppet arent you  
6018  mahmoud ahmadinejadi added the categoryanti se...  
6019  racisttrying to whitewash the terrorists fine ...  
6020  just because she has light skin doesnt mean an...  
6021  what the hell is that thing on the electoral m...  

[6022 rows x 3 columns]

In [16]:
train_data_col_shuffle = pd.DataFrame()
indices_moreToxic = []
col_1 = []
col_0 = []
random.seed(0)

for i in range(train_data.shape[0]):
    idx = round(random.uniform(0, 1))
    #print('index of more toxic',idx)
    
    indices_moreToxic.append(idx)#index of where the more toxic comment is 
        #1 for right column, 0 for left column 
    
    if idx == 1: 
        col_1.append( train_data['more_toxic'][i])
        col_0.append( train_data['less_toxic'][i])
        
    else:
        col_0.append(train_data['more_toxic'][i])
        col_1.append( train_data['less_toxic'][i])


train_data_col_shuffle['col_0'] = pd.Series(col_0)
#trans = pd.DataFrame(comment, columns = ['comment']) // another method of setting to df col

train_data_col_shuffle['col_1'] = pd.Series(col_1)
train_data_col_shuffle['more_toxic_col_idx'] = pd.DataFrame(indices_moreToxic)

train_data_col_shuffle


col_0  \
0      its not so much about the english language its...   
1      just read what mr george mcfly said here that ...   
2        fuck you fuck you motherfucker go die in a hole   
3                     jimbo wales is a gay little fucker   
4         a cup of coffee for you get fuckd with coffee    
...                                                  ...   
18059  i cant imagine anything more depressing than d...   
18060   give a reason when you accuse someone of vand...   
18061  additional evidence to above one of the collec...   
18062  hey gwernol yeah youre a schmuck face thats wh...   
18063  so you assholes are high on power like george ...   

                                                   col_1  more_toxic_col_idx  
0                           i hate drmies he is an idiot                   1  
1      i fuckingg love tacosthere the fuckingg best b...                   1  
2       a barnstar for you the original barnstar your...                   0  
3      i am one who thinks that zappas dad was of ara...                   0  
4      dude im not angry at you i just think youre a ...                   1  
...                                                  ...                 ...  
18059  i dont give a fuck.. it will get reposted so y...                   1  
18060  bullshit=there was no violation you removed fa...                   1  
18061  because you are a fggt do i know you because y...                   1  
18062  omg i am obssessed with twilight and it is my ...                   0  
18063  jack and jill come on delanoy wheres your sens...                   0  

[18064 rows x 3 columns]

In [17]:
#clean the input for predition data
cleaned_text = clean_tweets(data_to_test['text'])

data_to_test['text'] = pd.DataFrame(cleaned_text)
#data_to_test

In [18]:
# extract the labels from the train data
#y = trans.score.values
#X = trans.comment.values

from sklearn.feature_extraction.text import CountVectorizer

# initalize vectorizer: vectorize tweets for model building
vectorizer = CountVectorizer(binary=True, stop_words='english') #stop_words removed: a, the

# learn a vocabulary dictionary of all tokens in the raw documents
vectorizer.fit(list(cleaned_data_shuffle_row.more_toxic.values) + 
               list(cleaned_data_shuffle_row.less_toxic.values) + list(data_to_test.text.values))
    

# transform documents to document-term matrix
col0_vec = vectorizer.transform(train_data_col_shuffle.col_0)
col1_vec = vectorizer.transform(train_data_col_shuffle.col_1)
comments_2_score = vectorizer.transform(data_to_test["text"].values)
'''
# combine col0 and col1
col0_1_vec = vectorizer.transform(train_data_col_shuffle.col_0 + ' ' + train_data_col_shuffle.col_1)
'''

# for testing on the original clean more and less toxic col (unshuffled)
more_tox_test_vec = vectorizer.transform(test_data['more_toxic'].values)
less_tox_test_vec = vectorizer.transform(test_data['less_toxic'].values)

#val set 
more_tox_val_vec = vectorizer.transform(val_data['more_toxic'].values)
less_tox_val_vec = vectorizer.transform(val_data['less_toxic'].values)



In [19]:
empty_vec = vectorizer.transform([' ']*6022) #used for testing // a baseline comment to be 
#biranked against
empty_vec

<6022x46974 sparse matrix of type '<class 'numpy.int64'>'
	with 0 stored elements in Compressed Sparse Row format>

In [20]:
from scipy.stats import rankdata
# make a function to score the prediction and compare if the "lesser" toxic rated is lower prob of rated toxicity
def comp_toxicity (model, less_tox_val_vec, more_tox_val_vec):
    '''
    model is the trained model to be evaluated against the less and more toxic comments
    objective is to see if more toxic comments have a higher score

    less_tox_val_vec and more_tox_val_vec are the respective column in dataframe that contains the comments vectorized
    '''
    result = res = np.zeros((1,2))




    for i in range(less_tox_val_vec.shape[0]):
        result = rankdata([model.predict_proba(less_tox_val_vec[i]).tolist()[0][1], 
                 model.predict_proba(more_tox_val_vec[i]).tolist()[0][1]], method = 'ordinal' )
        result -= 1
        #print(result)
        res += result
        #print(res[0])
        '''
        if i == 5:
            break
        '''
    print ('final result: ',res[0])
    return res[0]



In [21]:
import scipy.sparse as sp

combined_2 = sp.hstack([col0_vec, col1_vec], format='csr') #concatenate the 2 columns for train
combined_2

<18064x93948 sparse matrix of type '<class 'numpy.longlong'>'
	with 901644 stored elements in Compressed Sparse Row format>

In [22]:
less_tox_empty_test_vec = sp.hstack([ empty_vec, less_tox_test_vec], format='csr')
less_tox_empty_vec = sp.hstack([empty_vec, less_tox_val_vec], format='csr') 
# need empty_vec on the left side, comp_toxicity assumes more toxic on the right -- toxicity prob score
less_tox_empty_vec

<6022x93948 sparse matrix of type '<class 'numpy.longlong'>'
	with 160583 stored elements in Compressed Sparse Row format>

In [23]:
more_tox_empty_vec = sp.hstack([ empty_vec, more_tox_val_vec], format='csr')
more_tox_empty_test_vec = sp.hstack([ empty_vec, more_tox_test_vec], format='csr')
more_tox_empty_test_vec

<6022x93948 sparse matrix of type '<class 'numpy.longlong'>'
	with 144111 stored elements in Compressed Sparse Row format>

In [27]:
#Logistic Regression

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(combined_2, train_data_col_shuffle.more_toxic_col_idx )
comp_toxicity(clf, less_tox_empty_vec , more_tox_empty_vec)
#print(pd.DataFrame(clf.predict(more_tox_empty_vec)).value_counts()) #does predict more toxic against baseline
#print(pd.DataFrame(clf.predict(less_tox_empty_vec)).value_counts()) # does predict ' ' as more toxic than non-toxic

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


final result:  [2143. 3879.]


array([2143., 3879.])

In [28]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=10, random_state=1)
clf.fit(combined_2, train_data_col_shuffle.more_toxic_col_idx )
comp_toxicity(clf, less_tox_empty_vec , more_tox_empty_vec)

final result:  [2018. 4004.]


array([2018., 4004.])

In [29]:
from sklearn import neighbors
#choose neighbours after the cv 
clf = neighbors.KNeighborsClassifier(n_neighbors=3)
clf.fit(combined_2, train_data_col_shuffle.more_toxic_col_idx )
comp_toxicity(clf, less_tox_empty_vec , more_tox_empty_vec)

final result:  [1412. 4610.]


array([1412., 4610.])

In [31]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(combined_2, train_data_col_shuffle.more_toxic_col_idx )
comp_toxicity(clf, less_tox_empty_vec, more_tox_empty_vec)

final result:  [2158. 3864.]


array([2158., 3864.])

In [32]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(combined_2, train_data_col_shuffle.more_toxic_col_idx )
comp_toxicity(clf, less_tox_empty_vec, more_tox_empty_vec)

final result:  [2171. 3851.]


array([2171., 3851.])

In [34]:
from sklearn import svm
C = 1.0
clf = svm.SVC(kernel='linear', C=C, probability = True)
clf.fit(combined_2, train_data_col_shuffle.more_toxic_col_idx )
comp_toxicity(clf, less_tox_empty_vec , more_tox_empty_vec)

clf = svm.SVC(kernel='rbf', C=C, probability = True)
clf.fit(combined_2, train_data_col_shuffle.more_toxic_col_idx )
comp_toxicity(clf, less_tox_empty_vec , more_tox_empty_vec)

clf = svm.SVC(kernel='sigmoid', C=C, probability = True)
clf.fit(combined_2, train_data_col_shuffle.more_toxic_col_idx )
comp_toxicity(clf, less_tox_empty_vec , more_tox_empty_vec)

clf = svm.SVC(kernel='poly', C=C, probability = True)
clf.fit(combined_2, train_data_col_shuffle.more_toxic_col_idx )
comp_toxicity(clf, less_tox_empty_vec , more_tox_empty_vec)




final result:  [2245. 3777.]
final result:  [2004. 4018.]
final result:  [2150. 3872.]
final result:  [1303. 4719.]


array([1303., 4719.])

# cross validation on different models

In [30]:
from sklearn.model_selection import cross_val_score


In [36]:
#Logistic Regression

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
cv_scores = cross_val_score(clf, combined_2, train_data_col_shuffle.more_toxic_col_idx, cv=10)
cv_scores.mean()

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


0.6305367461716801

In [37]:
#Random Forest

from sklearn.ensemble import RandomForestClassifier


clf = RandomForestClassifier(n_estimators=10, random_state=1)
cv_scores = cross_val_score(clf, combined_2, train_data_col_shuffle.more_toxic_col_idx,
                            cv=10)

print ('random forest: ',cv_scores.mean())

random forest:  0.6158664073086024


In [38]:
#KNN choosing best neighbour number 

from sklearn import neighbors


for n in range(1, 15):
    clf = neighbors.KNeighborsClassifier(n_neighbors=n)
    cv_scores = cross_val_score(clf,combined_2, train_data_col_shuffle.more_toxic_col_idx
                                , cv=10)
    print (n, cv_scores.mean())
    


1 0.5856401615227111
2 0.581653726341697
3 0.562055982609772
4 0.5824291959225874
5 0.5687549832354918
6 0.5799925354886037
7 0.5663183228015083
8 0.5728510572579504
9 0.5608938966894462
10 0.572020921468805
11 0.5589558509083354
12 0.5668720020150504
13 0.5541948960637265
14 0.5616684776380275


In [ ]:
#KNN 

from sklearn import neighbors

clf = neighbors.KNeighborsClassifier(n_neighbors=1)
cv_scores = cross_val_score(clf, combined_2, train_data_col_shuffle.more_toxic_col_idx,
                            cv=10)

cv_scores.mean()

In [40]:
#Naive Bayes
#usually not the best performance, but fast to train
from sklearn import preprocessing

from sklearn.naive_bayes import MultinomialNB

#scaler = preprocessing.MinMaxScaler()
scaler = preprocessing.MaxAbsScaler() #don't really need scaling since the input is already binary 
training_inputs_minmax = scaler.fit_transform(combined_2)

clf = MultinomialNB()
cv_scores = cross_val_score(clf, combined_2, train_data_col_shuffle.more_toxic_col_idx, cv=10)

print ('minmax scaled Baye\'s: ',cv_scores.mean())

minmax scaled Baye's:  0.6335798215503754


In [32]:
#SVM with kernel tuning

from sklearn import svm

C = 1.0
svc = svm.SVC(kernel='linear', C=C)
cv_scores = cross_val_score(svc,combined_2, train_data_col_shuffle.more_toxic_col_idx
                            , cv=10)
print ('linear kernel', cv_scores.mean())


svc = svm.SVC(kernel='rbf', C=C)
cv_scores = cross_val_score(svc, combined_2, train_data_col_shuffle.more_toxic_col_idx,
                            cv=10)
cv_scores.mean()
print ('rbf kernel', cv_scores.mean())


svc = svm.SVC(kernel='sigmoid', C=C)
cv_scores = cross_val_score(svc, combined_2, train_data_col_shuffle.more_toxic_col_idx
                            , cv=10)
cv_scores.mean()
print ('sigmoid kernel', cv_scores.mean())

svc = svm.SVC(kernel='poly', C=C)
cv_scores = cross_val_score(svc, combined_2, train_data_col_shuffle.more_toxic_col_idx
                            , cv=10)
cv_scores.mean()
print ('poly kernel', cv_scores.mean())

linear kernel 0.6178598853603037
rbf kernel 0.6434898184187124
sigmoid kernel 0.6374565872474521
poly kernel 0.5817658778676013


# try on colab: keras lstm, xgb 

Didn't try LSTM on biranked training, because the other models' accuracy didn't seem to improve with this biranked training of data transformation vs. the training done on rating aggregation.

In [28]:
!pip install xgboost

In [31]:
import xgboost as xgb

clf = xgb.XGBClassifier( eta = 0.6 ,objective = 'multi:softmax', num_class = 2) #eta higher starts losing acc -- lower is slower
cv_scores = cross_val_score(clf, combined_2, train_data_col_shuffle.more_toxic_col_idx
                            , cv=10)
print (cv_scores.mean())

0.6306466914380583


# Test data performance on the best model


In [26]:
#poly svm and nearest neighbour did the best on the validation set
from sklearn import neighbors, svm

C = 1

clf = svm.SVC(kernel='poly', C=C, probability = True)
clf.fit(combined_2, train_data_col_shuffle.more_toxic_col_idx )
comp_toxicity(clf, less_tox_empty_test_vec , more_tox_empty_test_vec)


clf = neighbors.KNeighborsClassifier(n_neighbors=2)
clf.fit(combined_2, train_data_col_shuffle.more_toxic_col_idx )
comp_toxicity(clf, less_tox_empty_test_vec , more_tox_empty_test_vec)

final result:  [1343. 4679.]
final result:  [1240. 4782.]


array([1240., 4782.])

# Best Model's Performance

K nearest neighbour with neighbours = 2's accuracy: 79.4 %.


# Improvement
Transfer learning on BERT sentiment analysis -- change out the last layer to fine tune the range of ranking capabilities. Can try to tune those pre-trained transformer models to biranked or aggregated data provided in this competition. See if this method offers higher prediction accuracy.